name: namecoin_expiry_integration_test

on:
  push


jobs:
  tests:
    runs-on:
      group: runners_v1
    steps:
      - name: Use Go = 1.23
        uses: actions/setup-go@v3
        with:
          go-version: '=1.23'
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: Set up gotestfmt
        uses: gotesttools/gotestfmt-action@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create temp directory
        run: |
          mkdir -p ./${{ github.run_attempt }}

      - name: Run Namecoin expiry integration tests
        run: |
          set -euo pipefail
          go test -json -timeout 5m -v -race -run 'TestNamecoinExpiryResolver' ./peer/tests/integration 2>&1 | tee ./${{ github.run_attempt }}/gotest-namecoin-expiry-int.log | gotestfmt

      - name: Upload Namecoin expiry integration test log
        uses: actions/upload-artifact@v4
        with:
          name: namecoin-expiry-integration-test-log
          path: ./${{ github.run_attempt }}/gotest-namecoin-expiry-int.log
          if-no-files-found: error
